"""Search metadata for PanWatch tools.

This metadata is intentionally separate from the model-facing JSON schemas.
The runtime can use it for discovery, while the host still owns executable
tool registration and permission decisions.
"""

from pan_agent import ToolRisk
from pan_agent_tool_research import ToolDataFreshness, ToolDescriptor

from .tool_metadata import ENTITY_LABELS_EN, localized_tool_presentation


PANWATCH_TOOL_DESCRIPTORS: tuple[ToolDescriptor, ...] = (
    ToolDescriptor(
        tool_name="get_portfolio",
        title="查询持仓",
        summary="查询用户实盘和模拟盘的持仓、仓位和组合摘要。",
        use_cases=["分析我的持仓", "查看组合", "诊断持仓风险"],
        keywords=["持仓", "组合", "仓位", "账户", "投资组合"],
        aliases=["我的股票", "持有哪些股票", "看看持仓"],
        domain="portfolio",
        capabilities=["portfolio_read", "risk_analysis"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=500,
        output_summary="持仓摘要和风险相关数据。",
    ),
    ToolDescriptor(
        tool_name="get_stock_quote",
        title="查询实时行情",
        summary="查询一只股票的最新价、涨跌幅和日内行情数据。",
        use_cases=["查询股价", "查看实时行情", "判断当前价格"],
        keywords=["行情", "股价", "价格", "报价", "涨跌", "实时"],
        aliases=["查股价", "最新价", "股票现在多少钱"],
        entities=["股票代码", "市场"],
        domain="market_data",
        capabilities=["quote", "market_data"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=1_000,
        output_summary="最新价、涨跌幅和交易状态。",
    ),
    ToolDescriptor(
        tool_name="find_research_candidates",
        title="发现研究候选",
        summary="从市场和持仓范围中筛选值得进一步研究的股票候选及机会信号。",
        use_cases=["发现投资机会", "筛选股票", "寻找研究候选"],
        keywords=["机会", "候选", "研究", "选股", "筛选", "信号"],
        aliases=["发现机会", "找股票机会", "推荐研究标的"],
        domain="investment_research",
        capabilities=["candidate_discovery", "signal_screening", "research"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=3_000,
        output_summary="候选标的、评分、风险和入场计划。",
    ),
    ToolDescriptor(
        tool_name="get_kline_summary",
        title="分析 K 线走势",
        summary="获取一只股票的均线、动量和近期 K 线技术指标摘要。",
        use_cases=["分析技术面", "查看趋势", "判断支撑压力"],
        keywords=["K线", "技术分析", "均线", "趋势", "动量", "支撑", "压力"],
        aliases=["走势", "技术面", "看图"],
        domain="market_data",
        capabilities=["technical_analysis", "kline", "trend_analysis"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=1_500,
        output_summary="K 线指标、趋势和支撑压力摘要。",
    ),
    ToolDescriptor(
        tool_name="get_stock_news",
        title="检索股票新闻",
        summary="检索一只股票最近七天的相关新闻、公告和消息摘要。",
        use_cases=["查询股票新闻", "查看公司消息", "了解最新公告"],
        keywords=["新闻", "资讯", "消息", "公告", "舆情"],
        aliases=["最近有什么新闻", "查公告", "看资讯"],
        domain="market_data",
        capabilities=["news", "event_research", "sentiment"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="近期新闻标题、来源和摘要。",
    ),
    ToolDescriptor(
        tool_name="search_stocks",
        title="搜索股票标的",
        summary="按股票代码或名称搜索股票清单，确认标的代码和市场。",
        use_cases=["搜索股票", "查股票代码", "确认股票名称"],
        keywords=["搜索股票", "股票代码", "股票名称", "标的", "查代码"],
        aliases=["找股票", "搜一下股票", "这只股票代码是多少"],
        entities=["股票代码", "股票名称", "市场"],
        domain="market_data",
        capabilities=["symbol_search", "instrument_lookup"],
        data_freshness=ToolDataFreshness.STATIC,
        estimated_latency_ms=1_000,
        output_summary="匹配的股票代码、名称和市场。",
    ),
    ToolDescriptor(
        tool_name="get_market_status",
        title="查询市场状态",
        summary="查询 A 股、港股和美股当前交易状态及交易时段。",
        use_cases=["查看市场是否开盘", "查询交易时间", "现在能交易吗"],
        keywords=["开盘", "收盘", "交易时间", "交易状态", "市场状态"],
        aliases=["现在开市吗", "今天开盘吗", "市场开了吗"],
        domain="market_data",
        capabilities=["market_status", "trading_calendar"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=100,
        output_summary="各市场交易状态、时区和交易时段。",
    ),
    ToolDescriptor(
        tool_name="get_hot_stocks",
        title="查询热门股票",
        summary="按涨幅或成交额查询指定市场的热门股票榜单。",
        use_cases=["查看热门股票", "找涨幅靠前的股票", "看成交额排行"],
        keywords=["热门股票", "涨幅榜", "成交额", "强势股", "异动股"],
        aliases=["股票排行榜", "今天哪些股票热门", "看看涨得好的股票"],
        entities=["市场", "排序方式", "数量"],
        domain="market_discovery",
        capabilities=["hot_stock_ranking", "market_screening"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="热门股票、价格、涨跌幅、成交额和成交量。",
    ),
    ToolDescriptor(
        tool_name="get_hot_boards",
        title="查询热门板块",
        summary="按涨幅、成交额或热度查询指定市场的热门板块和主题。",
        use_cases=["查看热门板块", "寻找强势行业", "了解市场主线"],
        keywords=["热门板块", "行业排行", "主题", "市场主线", "板块涨幅"],
        aliases=["哪些板块最强", "看行业热点", "查板块排行"],
        entities=["市场", "排序方式", "数量"],
        domain="market_discovery",
        capabilities=["hot_board_ranking", "theme_discovery"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="热门板块代码、名称、涨跌幅和成交额。",
    ),
    ToolDescriptor(
        tool_name="get_board_stocks",
        title="查询板块成分股",
        summary="查询指定板块中按涨幅、成交额或热度排序的成分股。",
        use_cases=["查看板块成分股", "找板块里的强势股", "分析行业个股"],
        keywords=["板块成分股", "行业个股", "板块股票", "板块内排行"],
        aliases=["这个板块有哪些股票", "看板块里的股票", "查板块成分"],
        entities=["板块代码", "排序方式", "数量"],
        domain="market_discovery",
        capabilities=["board_constituents", "board_screening"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_500,
        output_summary="板块成分股、价格、涨跌幅、成交额和成交量。",
    ),
    ToolDescriptor(
        tool_name="get_stock_fundamentals",
        title="查询股票基本面",
        summary="查询一只股票的估值、盈利、成长和财报期等基本面摘要。",
        use_cases=["分析基本面", "查看估值", "查询财务指标"],
        keywords=["基本面", "财务指标", "估值", "市盈率", "净利润", "ROE", "营收"],
        aliases=["看看公司基本面", "查财报指标", "估值怎么样"],
        entities=["股票代码", "市场"],
        domain="fundamentals",
        capabilities=["fundamentals", "valuation", "financials"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="估值、盈利、成长和最新财报期指标。",
    ),
    ToolDescriptor(
        tool_name="get_capital_flow",
        title="查询资金流向",
        summary="查询一只股票的主力、超大单和大单等资金流向摘要。",
        use_cases=["查看资金流向", "分析主力资金", "判断资金进出"],
        keywords=["资金流", "主力资金", "净流入", "大单", "超大单"],
        aliases=["主力在买入吗", "资金进出怎么样", "看主力动向"],
        entities=["股票代码", "市场"],
        domain="market_data",
        capabilities=["capital_flow", "money_flow"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="主力、超大单、大单和近 5 日资金流向。",
    ),
    ToolDescriptor(
        tool_name="get_dragon_tiger",
        title="查询龙虎榜",
        summary="查询指定交易日的龙虎榜上榜股票、上榜原因和买卖金额。",
        use_cases=["查询龙虎榜", "查看游资动向", "分析上榜股票"],
        keywords=["龙虎榜", "上榜", "游资", "机构席位", "净买入"],
        aliases=["看龙虎榜", "今天龙虎榜", "查上榜股票"],
        entities=["交易日期", "市场"],
        domain="market_discovery",
        capabilities=["dragon_tiger", "institution_activity"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_500,
        output_summary="上榜股票、上榜原因、收盘表现和买卖金额。",
    ),
    ToolDescriptor(
        tool_name="get_price_alerts",
        title="查询价格提醒",
        summary="查询用户已创建的价格提醒、触发条件和启用状态。",
        use_cases=["查看提醒", "查询价格预警", "看看已有监控"],
        keywords=["提醒", "价格提醒", "预警", "监控", "触发条件"],
        aliases=["我的提醒", "有哪些价格预警"],
        domain="price_alerts",
        capabilities=["alert_read", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=300,
        output_summary="提醒 ID、标的、条件和启用状态。",
    ),
    ToolDescriptor(
        tool_name="update_price_alert",
        title="修改价格提醒",
        summary="修改一条价格提醒的目标价、方向或启用状态。",
        use_cases=["修改提醒", "调整预警价格", "停用价格监控"],
        keywords=["修改提醒", "调整预警", "更新价格提醒"],
        aliases=["改提醒", "调整提醒条件"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["修改用户价格提醒"],
    ),
    ToolDescriptor(
        tool_name="delete_price_alert",
        title="删除价格提醒",
        summary="删除一条价格提醒及其历史命中记录。",
        use_cases=["删除提醒", "取消价格监控", "清理预警"],
        keywords=["删除提醒", "取消提醒", "移除预警"],
        aliases=["删掉提醒", "不要这个提醒了"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["删除用户价格提醒"],
    ),
    ToolDescriptor(
        tool_name="create_price_alert",
        title="创建价格提醒",
        summary="为已收录的股票创建盘中价格提醒。",
        use_cases=["设置价格提醒", "创建价格预警", "监控突破或跌破"],
        keywords=["创建提醒", "设置提醒", "价格预警", "突破", "跌破"],
        aliases=["提醒我", "设置价格监控"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["创建用户价格提醒"],
    ),
)


def localized_tool_descriptors(language: str) -> tuple[ToolDescriptor, ...]:
    """Expose search metadata in the same language as the model-facing tools."""
    if language != "en-US":
        return PANWATCH_TOOL_DESCRIPTORS

    localized: list[ToolDescriptor] = []
    for descriptor in PANWATCH_TOOL_DESCRIPTORS:
        title, summary = localized_tool_presentation(
            descriptor.tool_name,
            descriptor.title,
            descriptor.summary,
            language,
        )
        localized.append(
            descriptor.model_copy(
                update={
                    "title": title,
                    "summary": summary,
                    "use_cases": [title],
                    "keywords": [title, descriptor.tool_name],
                    "aliases": [descriptor.tool_name],
                    "entities": [
                        ENTITY_LABELS_EN.get(entity, entity)
                        for entity in descriptor.entities
                    ],
                    "output_summary": summary,
                    "side_effects": (
                        [summary] if descriptor.side_effects else []
                    ),
                }
            )
        )
    return tuple(localized)
